spring.application.name=SLAProject

# Database configuration

spring.datasource.url=jdbc:postgresql://192.168.100.176:5432/CommonDefinition?useSSL=false&serverTimezone=UTC
spring.datasource.username=postgres
spring.datasource.password=demo@123